### ISSUE TITLE
Stuck on screen "Welcome to Bullworth"

### ISSUE THREAD

**Issue by Enroobs** [CookiePLMonster/SilentPatchBully#1]
I installed the patch and was able to go into the main menu settings and changed them to 1920 x 1080 and set anti-aliasing to 8 also set shadows to high. I choose start the game and it freezes, in task manager its says "not responding". If there is any fix to this or a future fix to this please let me know! Thank you

**Comment by Enroobs** [comment]
Using Steam Version

**Comment by CookiePLMonster** [comment]
Is this happening at all times? I had this happen a few times but couldn't make it fully reproducible.

Also I found out it may be caused by MiniDumper not exactly working right - I will be shipping an updated version of it in the next build!

**Comment by Enroobs** [comment]
Yeah I tried at least ten times to see if it only happens once but it seem to do it every time I try to start the game.

**Comment by CookiePLMonster** [comment]
I believe a faulty MiniDumper.asi may be causing that - for the time being, try removing/renaming it to see if it helps. I have already fixed it for Build 2 so would be good to get a confirmation that it's really this causing the issue.

**Comment by Enroobs** [comment]
Okay thank you

**Comment by Enroobs** [comment]
All I had to do was rename it. Now the game works perfectly.

**Comment by CookiePLMonster** [comment]
So just like I thought - can you check again with a MiniDumper I linked in #4?

**Comment by Enroobs** [comment]
I tried it with the one you linked in #4 and it froze in the first screen again I also tried renaming it but that didn't work either. I also noticed that when I go into the silent patch settings and set the fps to standard 30 it works and gets past the screen with the MiniDumper renamed and if the fps was higher i wouldn't get past the screen.

**Comment by Enroobs** [comment]
The first MiniDumber with the public beta release

**Comment by CookiePLMonster** [comment]
Good to know... what did you try it with, then? if you chose FPSLimit=0 (uncapped) and had Vertical Sync OFF, then it could have caused some havoc.

**Comment by Enroobs** [comment]
No I haven’t changed to uncapped at all so far but I do leave v-sync on

**Comment by CookiePLMonster** [comment]
> when I go into the silent patch settings and set the fps to standard 30 it works and gets past the screen with the MiniDumper renamed and if the fps was higher i wouldn't get past the screen.

So what FPS did you set it to so you had this issue?

**Comment by Enroobs** [comment]
At 120

**Comment by CookiePLMonster** [comment]
Try something lower, from what I gathered game starts playing at double
speed at over 120FPS - may be related to your problem.

**Comment by Enroobs** [comment]
Okay I’ll try that

**Comment by CookiePLMonster** [comment]
Most likely solved with Build 2! Feel free to reopen if the issue is still occuring.
