### ISSUE TITLE
Balls of Snow bug

### ISSUE THREAD

**Issue by LacosteWave** [CookiePLMonster/SilentPatchBully#10]
Hi, i found a bug in the mission ''Balls of Snow'', i can't beat that mission due to the game not reloading snowballs. I'm with the 1.200 patch and it's a clean version of the game, if someone knows some fix let me know, please.

**Comment by CookiePLMonster** [comment]
Pretty sure this is related to FPS, as in this is one of the missions which break with 60 FPS. Should restore back to 30 FPS for this mission.

**Comment by LacosteWave** [comment]
Yeah, it was that, thanks for the patch too.
