### ISSUE TITLE
stuck on loading screen while i run the game 

### ISSUE THREAD

**Issue by aymenrenai** [CookiePLMonster/SilentPatchBully#11]
i have proplem once i run the game he stuck on loading screen the screen of the begin of the game please help me

**Comment by aymenrenai** [comment]
please responde

**Comment by CookiePLMonster** [comment]
You are really not being clear - which loading screen exactly? Did you change the FPS cap? Does the problem also happen without SPBully?

**Comment by CookiePLMonster** [comment]
Build 2 is now out! I do not know if this specific issue has been fixed, though - but it's still worth a test!

**Comment by CookiePLMonster** [comment]
Locking due to inactivity.
