### ISSUE TITLE
bully is now vey fast but not as an fps way

### ISSUE THREAD

**Issue by MaG1KS** [CookiePLMonster/SilentPatchBully#15]
when i installed this patch my bully game is now faster by speed jimmy runs very quik and the game looks like im watching a video on youtube that is speeden up

**Comment by CookiePLMonster** [comment]
Have you uncapped FPS? Sure sounds like it.

**Comment by CookiePLMonster** [comment]
I'm going to assume this was caused by uncapped FPS and playing at over 120FPS. Feel free to reopen if that is **not** the case!
