### ISSUE TITLE
Bully crashes on mods, ex: Supermod/Insanity

### ISSUE THREAD

**Issue by tomjfmu3** [CookiePLMonster/SilentPatchBully#19]
I tried other mods and they worked, it might be the mod's fault but I want to know.
However with vanilla bully, and super mod it worked fine.

[crashes.zip](https://github.com/CookiePLMonster/SilentPatchBully/files/2040640/crashes.zip)

**Comment by tomjfmu3** [comment]
i checked and now it crashes with super mod, i'll give info because now i'm gonna try it vanilla

**Comment by tomjfmu3** [comment]
closed, it was the mods

**Comment by tomjfmu3** [comment]
[crashes2.zip](https://github.com/CookiePLMonster/SilentPatchBully/files/2040872/crashes2.zip)

update, now more crash logs of insanity edition and supermod

**Comment by CookiePLMonster** [comment]
Build 2 is now out! I do not know if this specific crashes have been fixed, though - but it's still worth a test!

**Comment by tomjfmu3** [comment]
thanks, but it's not the os, it's probably the mods fault, i'm going to close this.
