### ISSUE TITLE
Still keeps crashing

### ISSUE THREAD

**Issue by JJ2011** [CookiePLMonster/SilentPatchBully#2]
Hello,
Before I had applied the patch, the game could be played until 20 min or so, before crashing. But after I had applied the patch, it cannot be played even for 20 min. It works for hardly 5 min... you get the point ;)
However, the graphics and framerate has improved since I've applied the patch, so thanks for that! 
P.S. I am not able to attach the .DMP file here

**Comment by CookiePLMonster** [comment]
You should be able to pack it into a .zip archive and then upload. Please do it, since you're the first person to report that things got **worse** with a patch applied.

**Comment by CookiePLMonster** [comment]
Anything?

**Comment by JJ2011** [comment]
[Bully DMP file.zip](https://github.com/CookiePLMonster/SilentPatchBully/files/1799218/Bully.DMP.file.zip)
I have uploaded the DMP file... but surprisingly, when i played Bully recently, it had worked for more than an hour! I'm not sure if it was one-time thing, but i'll reply here if it crashes again.

**Comment by JJ2011** [comment]
It has crashed again **:(** It worked for about 5 minutes again... I'll upload the file.
[Bully Crash.zip](https://github.com/CookiePLMonster/SilentPatchBully/files/1799234/Bully.Crash.zip)

**Comment by CookiePLMonster** [comment]
You uploaded the same file twice.

Still, this is a crash I believe I have seen already - worth investigating.

**Comment by CookiePLMonster** [comment]
For the record, do you have any mods in your game?

**Comment by JJ2011** [comment]
No, I don't use mods in my games. ;)
But are we to set a compatibility mode? Because I unchecked that and the run as administrator too.

**Comment by CookiePLMonster** [comment]
You can try - but ultimately my goal is to make the game work flawlessly without any compatibility modes. For the time being, you can try messing with them but the fun thing is, I never had any crashes myself **unless** I set compatibility mode!

**Comment by CookiePLMonster** [comment]
@JJ2011 what are your graphics settings? Antialiasing? Vertical sync enabled/disabled? Shadows set to High/Low/Off?

**Comment by JJ2011** [comment]
Resolution: 1366x768
Antialisasing: OFF
Vertical sync: OFF
Shadows: HIGH

**Comment by jaYRacOmintRhu** [comment]
Try keepin' V-Sync on and Shadows off. There's somethin' glitchy about them. Not sure though. Silent still the man.

**Comment by CookiePLMonster** [comment]
You may not be wrong... while I can play on shadows at High and Vsync on just fine, I do recall seeing someone claim disabling shadow helps with stability.

Either way, that's good info. For Build 2 I'll need to come up with a workaround (since I still don't know the proper fix) for this crash you are having (since it's relatively common) and maybe add some logging to it.

**Comment by CookiePLMonster** [comment]
Build 2 is now out! I do not know if this specific crash has been fixed, though - but it's still worth a test!

**Comment by CookiePLMonster** [comment]
No response for a loong time, so I am going to close it. If it still persists, please reopen.
