### ISSUE TITLE
That shit keeps on crashing!!!

### ISSUE THREAD

**Issue by saimalihere** [CookiePLMonster/SilentPatchBully#20]
I applied the patch but still no use :(

**Comment by CookiePLMonster** [comment]
Have you tried with an updated MiniDumper.asi from one of the Issues in there? Saying "this shit keeps on crashing" literally can't be less helpful.

**Comment by CookiePLMonster** [comment]
I'm going to assume this is resolved. If it's not, feel free to open a new issue, but please be more informative and maybe also refrain from calling it like you did.
