### ISSUE TITLE
Crash when loading game

### ISSUE THREAD

**Issue by RAS-2112** [CookiePLMonster/SilentPatchBully#24]
### Description
Loading an existing save game after running the game for a while results in a crash to desktop. I've only encountered this issue after playing the game for at least 30 minutes or so. Loading an existing save prior to this works as expected. Once this crash has occurred, the game will no longer launch until Stream is restarted.

### Steps to recreate
1. Launch game
2. Load an existing save game 
3. Leave running for 30 minutes or so (exact timing unknown, all crashes have been encountered after playing for some time, however)
4. Load an existing save game from the start menu

### Additional Details
* Windows 10 Home (1803, 17134.165)
* Bully: Scholarship Edition (Version 1.2, Steam)
* SilentPatchBully (Build 1 (BETA))
* [Bully.exe.20180715205621.dmp.zip](https://github.com/CookiePLMonster/SilentPatchBully/files/2196108/Bully.exe.20180715205621.dmp.zip)

**Comment by CookiePLMonster** [comment]
Build 2 is now out - is this still a problem? I think it's not resolved by my current changes, but then again I haven't tried reproducing it yet.

**Comment by RAS-2112** [comment]
Unfortunately, the issue remains unresolved as of [Build 2 (BETA)](https://github.com/CookiePLMonster/SilentPatchBully/releases/tag/BUILD-2-TEST). In this instance, I had the game running for around 20 minutes or so before attempting to load an existing save from the start menu.

I've also since found that attempting to quit to the main menu will also result in the same crash. Attached `.dmp` file is from crash encountered upon loading an existing save game.

To clarify, the crashes are encountered when the user is already playing on a loaded save game, i.e. has full control of Jimmy and is playing, then loads a save game from the start menu. I've updated the steps to reproduce to make this a little clearer.

- [Bully.exe.20180723195931.zip](https://github.com/CookiePLMonster/SilentPatchBully/files/2220687/Bully.exe.20180723195931.zip)

**Comment by CookiePLMonster** [comment]
Build 3 is now out!

> I had the game running for around 20 minutes or so before attempting to load an existing save from the start menu.

This sure sounds like one of [audio related crashes which Build 3 fixes](https://cookieplmonster.github.io/2020/03/07/silentpatch-bully-r3/), so I am going to go ahead and close this issue. If you're still encountering it after upgrading, please reopen!
