### ISSUE TITLE
High frame rate issues

### ISSUE THREAD

**Issue by Keith94** [CookiePLMonster/SilentPatchBully#25]
There's supposedly a number of [high frame rate issues](https://pcgamingwiki.com/wiki/Bully:_Scholarship_Edition#High_frame_rate) related to this game... I was wondering if it would be possible to fix them directly or even workaround them; i.e. automatically cap the FPS in specific situations.

What do you think?

**Comment by CookiePLMonster** [comment]
While that would be cool, I'm not yet sure if I am going to bother - current crashing issues are much more important than this.

But yeah I agree - dynamic FPS cap would probably be the best approach!

**Comment by Keith94** [comment]
Thanks for the reply. Yes, crashing issues are a priority while this can be for the future :)
