### ISSUE TITLE
Still crashing

### ISSUE THREAD

**Issue by Wolflonnie** [CookiePLMonster/SilentPatchBully#26]
Did most of Act 1 in one piece thanks to your patch.
Started Act 2, and I'm experiencing crashes. One randomly happened when crossing the bridge the northest part of the city.

Save: https://www.sendspace.com/file/5k03s6

**Comment by Wolflonnie** [comment]
Aaand more of them. https://www.sendspace.com/file/a642t6
Sometimes it's very frequent, other times I can play 1+ hour without crashes.

**Comment by CookiePLMonster** [comment]
With Build 3 released, those crashes should be resolved. If you're still encountering issues, please reopen!
