### ISSUE TITLE
Bully keeps crashing still.

### ISSUE THREAD

**Issue by RexyFox** [CookiePLMonster/SilentPatchBully#37]
First, i have a non-steam version of the game by Mr DJ. I was experiencing crashes last night and I downloaded this patch and my game worked ok after I downloaded the patch. But when I got the 2nd modupdater thingy my Bully keeps exiting out by itself but the icon is still on the taskbar. After a while,the icon disappears too. I try to click on the icon but it wont open. I tried to reinstall the patch, it worked but then the same thing happened. here are the .dmp files.
[Bully .dmp files (rexyfox).zip](https://github.com/CookiePLMonster/SilentPatchBully/files/3063211/Bully.dmp.files.rexyfox.zip)

**Comment by xamzy** [comment]
We in the Bully community don't advocate using pirated versions of Bully. Buy the game and it will most likely work.

**Comment by RexyFox** [comment]
Bought the game and works fine, thanks.
