### ISSUE TITLE
Game doesn't launch while streaming

### ISSUE THREAD

**Issue by DavidSrno** [CookiePLMonster/SilentPatchBully#4]
Maybe a problem with OBS?!

The game launch with the patch installed while im not streaming, the problem is when I try to start it during streaming it just don't start..

**Comment by CookiePLMonster** [comment]
That is indeed the case! It's my fault, I made MiniDumper much more paranoid than it should be so it's logging too much.

Temporary fix: Remove/rename MiniDumper.asi when you want to get the game to run with OBS.

A proper fix will arrive with Build 2.

**Comment by DavidSrno** [comment]
Wow, so fast! Thank you so much!

**Comment by CookiePLMonster** [comment]
While I have your attention, does this version of MiniDumper cause issues with OBS? It shouldn't.

[MiniDumper.zip](https://github.com/CookiePLMonster/SilentPatchBully/files/1800296/MiniDumper.zip)

**Comment by DavidSrno** [comment]
Yap, it's working better with it that without it!

Thank you so much for this fix!

**Comment by CookiePLMonster** [comment]
Build 2 is now out and contains a new MiniDumper, so this one is solved!
