### ISSUE TITLE
Higher FPS == Faster Game speed

### ISSUE THREAD

**Issue by WhatzGames** [CookiePLMonster/SilentPatchBully#48]
So very simple, for me loading the dll is not a problem.
But I've noticed, that the speed is increasing as i increase the fps…
so for example…
I set the FPS limit to 0 and then i get about 1600 to 2000 fps in main menu. (vsync is off btw.)
this results in the time that the menu waits for input is run through in the shortest possible time and thus my game starts almost immediately after startup, without me giving it any input.
also in game the time passes way faster. with about 60 fps it is hardly noticable, but with like 200 fps, you see the difference.

I could record it, if that would be of any help.

**Comment by CookiePLMonster** [comment]
This is a known issue when you go above 60FPS and fixing this is currently not in the scope of the patch.

I don't recommend uncapping FPS ever.
