### ISSUE TITLE
Not working with BullyMP

### ISSUE THREAD

**Issue by xLaStar** [CookiePLMonster/SilentPatchBully#5]
It keeps crashing with BullyMP

**Comment by CookiePLMonster** [comment]
Known issue - debugging code left in SPBully detects internal errors BullyMP has. Should be fixed on their part (and devs are already aware so hopefully won't take long).

**Comment by xLaStar** [comment]
Thanks for the quick answer, ill close the issue then and hopefully they'll relase the fix sooner
