### ISSUE TITLE
Glitch in mission "Balls of Snow".

### ISSUE THREAD

**Issue by V4T3** [CookiePLMonster/SilentPatchBully#53]
During this mission, after throwing a snowball, the next one does not appear in the hands of the hero.
By default, it works so that after throwing the first snowball, the second appears in a moment.

Game Version: Steam

BTW. Sorry for my English.

**Comment by xamzy** [comment]
This is an issue that occurs at 60fps, not the patch itself. Change your FPS in the settings.ini to 30, and then try again. :)
