### ISSUE TITLE
Is the mod compatible with the ThirteenAG's widescreen fix?

### ISSUE THREAD

**Issue by ghost** [CookiePLMonster/SilentPatchBully#57]
https://thirteenag.github.io/wfp#bully

Both mods use a `dinput8.dll` file.

**Comment by CookiePLMonster** [comment]
`dinput8.dll` is just an ASI loader so yes - just use a newer one out of the two. What truly matters is that the `.asi` files are there.

**Comment by ghost** [comment]
Thank you for the prompt confirmation. I'll likely switch to the latest [Bully SP release](https://github.com/CookiePLMonster/SilentPatchBully/releases).
