### ISSUE TITLE
Crashed just as fast. 

### ISSUE THREAD

**Issue by kasperchaz585** [CookiePLMonster/SilentPatchBully#6]
i downloaded your file. unpacked and brought everything over too steam- steamapps -common - bully scholorship edition. drag drop. started up bully , got from the school office too the bike store by the beach started a favor mission..crash. i am a little new too bug fixes only game i really tampered with them for was skyrim but it was easy fixes. So anyways then i restarted it. played flawless for about 3 hours then again stopped working. (bully.exe has topped working) it wont let me send a report it.

**Comment by kasperchaz585** [comment]
and where do i upload them from?

**Comment by kasperchaz585** [comment]
i searched dmp in the folder nothing shows up

**Comment by CookiePLMonster** [comment]
They are supposed to be in your game directory - if you don't have them after a crash, it's likely you didn't install the patch correctly.

**Comment by kasperchaz585** [comment]
im a noob but i follow directions easy if you want to link me a quick how to i can do that for you. and my files are set to kernel i know that much. and shit all i gotta do is export the files right

**Comment by CookiePLMonster** [comment]
`my files are set to kernel i know that much. and shit all i gotta do is export the files right`

I literally have no idea what you said here.

**Comment by kasperchaz585** [comment]
![mvimg_20180312_174951](https://user-images.githubusercontent.com/37274968/37311602-49d27fa4-261e-11e8-941d-cd3cacb62d05.jpg)
its just a dump file setting if udk what im talking about then its probably not important

**Comment by CookiePLMonster** [comment]
What the hell did you do? You downloaded the source code and not the correct package...

Please try again **properly** and feel free to reopen this issue once you try with a correct package.

**Comment by Misiek1029** [comment]
bruh
