### ISSUE TITLE
Still crashing

### ISSUE THREAD

**Issue by xLaStar** [CookiePLMonster/SilentPatchBully#7]
I still encounter the same crashes that I was encountering before the patch in free roam
[Bully Scholarship Edition.zip](https://github.com/CookiePLMonster/SilentPatchBully/files/1813653/Bully.Scholarship.Edition.zip)

**Comment by xLaStar** [comment]
Apparently with v-synch on its fixed 1 hour without any crash

**Comment by xLaStar** [comment]
[Bully.exe.20180315053110.zip](https://github.com/CookiePLMonster/SilentPatchBully/files/1814078/Bully.exe.20180315053110.zip)

**Comment by xLaStar** [comment]
Still crashing ...

**Comment by CookiePLMonster** [comment]
You're not the first person to state you're having more frequent crashes
with vsync off... Since the most common crash currently is related to
models (haven't had a chance to look at your crashes yet) maybe it really
is a factor... I need to give it a go!

**Comment by xLaStar** [comment]
V-Sync on did help with stability but it still crash sometimes, last dmp file was recorded with v-sync on btw

**Comment by CookiePLMonster** [comment]
Build 2 is now out! I do not know if this specific crash has been fixed, though - but it's still worth a test!

**Comment by CookiePLMonster** [comment]
No response for a loong time, so I am going to close it. If it still persists, please reopen.
