### ISSUE TITLE
Crash at Title Screen With Mod Unless Tapping A

### ISSUE THREAD

**Issue by RinMaru** [CookiePLMonster/SilentPatchBully#72]
Bully Scholarship Edition Patch 1.200
Using Silent Patch Beta 3, Screen Set to 30FPS and MM set to on.
Using [Bully Anniversary Edition Hud ](https://www.moddb.com/games/bully-scholarship-edition/downloads/bully-scholarship-edition-anniversary-edition-hud) 
Using [Unofficial Enhancements](https://www.moddb.com/games/bully-scholarship-edition/downloads/bully-scholarship-edition-unofficial-enhancements)

Windows 10 x64 21H1 19043.1055
AMD Ryzen 5 5600X
20GB DDR4 RAM Two 8GB Sticks Plus a 4GB Stick
AMD RX 480 4GB

Ever since installing these mods the game will start up normally but once you reach the title screen the game will quickly die unless you spam the A button to start game. Once you exit the game and get taken back to the Start Screen no crash Occurs. I attached a DMP file.

[Bully.exe.10096.zip](https://github.com/CookiePLMonster/SilentPatchBully/files/6646216/Bully.exe.10096.zip)
[Bully.exe.2096.zip](https://github.com/CookiePLMonster/SilentPatchBully/files/6646361/Bully.exe.2096.zip)
[Bully.exe.5628.zip](https://github.com/CookiePLMonster/SilentPatchBully/files/6646367/Bully.exe.5628.zip)

**Comment by RinMaru** [comment]
Ive narrowed the Crash down to the World.img when its repacked with the fixed models in Unofficial Enhancements. What models are breaking it i cant be sure.

**Comment by CookiePLMonster** [comment]
I'm not sure how this is a SPBully issue - you should either narrow that down on your own or check with the author(s?) of Unofficial Enhancements.
