### ISSUE TITLE
Auto-skips cutscenes

### ISSUE THREAD

**Issue by Carnotauros** [CookiePLMonster/SilentPatchBully#74]
When playing with the mod, the game auto skips the cutscenes near the end

**Comment by xamzy** [comment]
Hello there! 
I've done a speedrun of a meme category named "Cutscene%" - in which we watch all the cutscenes. 

In the speedrun, we are required to use SilentPatch - and I never noticed any cutscenes being autoskipped anywhere; neither has anyone else reported this. 
If you could check you've not got any conflicting mods (Perhaps a menu mod, eg; supermod, havoc's menu) and then perhaps return us some video footage of this happening, that would be much appreciated. 

Thanks.

**Comment by Carnotauros** [comment]
I don't have any other mods than silentpatch, I'll record a video and post here

**Comment by Carnotauros** [comment]
It should also be noted that I play the game with Windows XP compatibility mode and forced administrator (as this was another fix for crashes), do you think that this could influence the cutscene scips?

**Comment by Carnotauros** [comment]
Also found this: https://steamcommunity.com/app/12200/discussions/0/1710690018669840714/
I had FPS cap set to 144, could possibly be the problem here

**Comment by Carnotauros** [comment]
Update: Set FPS limit to 30 and the cutscenes weren't autoscipped

**Comment by Carnotauros** [comment]
> Update: Set FPS limit to 30 and the cutscenes weren't autoscipped

60 FPS also worked fine

**Comment by xamzy** [comment]
Turn off Comparability mode and run as admin. They don't need to be used. 
Only 30fps should be used. 60fps breaks collision objects and anything over that will make the game run at double speed.

**Comment by CookiePLMonster** [comment]
Closing then. As @xamzy said, only 30FPS is supported, an ability to lift the limit up is only a courtesy so you may freeroam at 60FPS.
