### ISSUE TITLE
Crashes when I load a new area

### ISSUE THREAD

**Issue by MCer12369** [CookiePLMonster/SilentPatchBully#77]
I already have a save file (which I load up), and it crashes once I leave the safehouse. Please help!                                  My PC Specs: (my PC is a 2010-2011 laptop btw) Intel(R) Core(TM) i5 CPU M 560 @ 2.67GHz,     4 cores,     8 GB of RAM,   NVIDIA NVS 3100M,     Windows 10 32-bit (swear it is 64-bit). I have SilentPatch, widescreen fix, and extended draw distance installed. I have the steam version of Bully, and use 30 FPS. I have installed SilentPatch correctly. The exact steps in order to reproduce it is load up the game, load up an existing save, and once I leave the save place, it infinitely loads.

**Comment by xamzy** [comment]
You're gonna have to give us more info than just "this happens. give help." 

Have you installed SPBully correctly? If so, it should produce a crashdump, can you upload it and send it to us along with your save file? 
Can you explain the exact location this is happening? Can you tell us steps to reproduce the crash - eg; what you do in order every single time to make it happen.  
Can you list your PC specs / version of the game you have (Disc, Steam, RGL...) How you launch it, what FPS you play on etc etc. 

The more info, the more we can help you. 
-amzy.

**Comment by MCer12369** [comment]
How do I send my save file if the game's files are on a external storage space?

**Comment by xamzy** [comment]
Save files are always in Documents > Bully Scholarship Edition - on your C:\ Drive, regardless of where you have the game installed. 
Do you have a crashdump which originates from that specific crash? (which can be found in your game directory)

I wasn't aware there even was a 32 Bit version of Windows 10, but hey. 
Is it possible you could try uninstalling the mods you have, and seeing if it still crashes before sending us anything, though? It could be that something else you have installed is interfering with the game, and it's not directly a problem with the game itself.

Thanks.

**Comment by MCer12369** [comment]
Sure will

**Comment by MCer12369** [comment]
https://drive.google.com/file/d/12YkmHM6S74XqGGi9dvB3_ByOPLb-IX_9/view?usp=sharing      this is my bully file. There is no crashdump in my bully directory.
