### ISSUE TITLE
Patch issue

### ISSUE THREAD

**Issue by AkbarNurahman** [CookiePLMonster/SilentPatchBully#82]
How to update version of this game? Please help
I have downloaded the patch v1.200 and try to install but when i open the game it doesn't update, the version still v1.154
![1632218729653550626473351832903](https://user-images.githubusercontent.com/91124516/134152371-feb6ea07-66da-42d6-9d9e-621a89077900.jpg)
 
And this is where I downloaded the patch
https://support.rockstargames.com/articles/200149976/Bully-Scholarship-Edition-Patch-1-200-PC-Only

(sorry my first language is not English)

**Comment by xamzy** [comment]
How did you obtain the game? Did you buy it through Steam or RockstarGamesLauncher? Or do you have a physical disc?

**Comment by AkbarNurahman** [comment]
> How did you obtain the game? Did you buy it through Steam or RockstarGamesLauncher? Or do you have a physical disc?


i downloaded from oceangames, cracked games 
i don't have steam

**Comment by xamzy** [comment]
Sorry, we can't help you; that's due to you having a cracked copy. 
Please purchase a copy of the game, and both EFIGS and SilentPatch will work fine.
