### ISSUE TITLE
modupdater.asi accused as trojan

### ISSUE THREAD

**Issue by lurquera** [CookiePLMonster/SilentPatchBully#92]
This happens when VirusTotal checks the file. 
I have no programming knowledge, but I found it a bit strange. I'm not accusing anyone, I'm just looking for an explanation for this.
![image](https://user-images.githubusercontent.com/99725140/154069310-4bb1023e-dcd2-4f90-a40c-f5f661d7e625.png)
link: https://www.virustotal.com/gui/file/669150e124d1c0634b9fe40d9ed704438415614d90eddf130946c29d60e5ccf0

**Comment by xamzy** [comment]
It's used to update the package; this is just a generic false positive due to over-detection. 
It's used in a lot of ASI mods to help update said mods. 
You can ignore this detection :)

**Comment by lurquera** [comment]
Thank you so much, i didn't even know this could happen
