### ISSUE TITLE
Steam Deck/Linux Support

### ISSUE THREAD

**Issue by Xitro01** [CookiePLMonster/SilentPatchBully#97]
I've copied the files into the root directory of Bully on my Steam Deck, but the patch doesn't seem to work.
Any ideas how to fix this?

**Comment by CookiePLMonster** [comment]
I never checked my patches on anything using Proton, but I had those setup instructions given to me:
https://cookieplmonster.github.io/setup-instructions/#proton-wine

They should at least partially transfer to Steam Deck I think.

**Comment by Xitro01** [comment]
Awesome, thanks!

Simply adding "WINEDLLOVERRIDES="dinput8=n,b" %command%" to my Launch Options was enough!

Thanks again!

**Comment by CookiePLMonster** [comment]
Thanks, that's good to know! I'll check this on my own Deck and update the setup instructions accordingly.
